spring.application.name=sakila-rental

spring.datasource.url=jdbc:postgresql://localhost:5432/sakila
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
